# 形状绘制
- 形状
    - 线段，矩形，圆形，三角形，任意多边形
- 文字

- 图片 

In [15]:
import cv2
import numpy as np

img = cv2.imread("./eunha.jpg",1)

# 1. 线段绘制

- API:
    - cv2.line()
        - 参数1：目标图片数据
        - 参数2：线段绘制的起始位置
        - 参数3：线段绘制的终止位置
        - 参数4：颜色 color bgr
        - 参数5：线段宽度
        - 参数6：线段类型,type，例：防锯齿化 

In [4]:
dst_line = np.zeros((500,500,3), np.uint8)

cv2.line(dst_line, (100,100), (400,400), (0,0,255))

cv2.line(dst_line, (100,200), (400,200), (0,255,255), 20)

cv2.line(dst_line, (100,300), (400,300), (0,255,0), 20, cv2.LINE_AA)    # type

# 绘制三角形：
# 三角形第一条边的终止位置，是第二条边的起始位置。第三条线段的终止位置，是第一条线段的起始位置
cv2.line(dst_line, (200,150), (50,250), (25,100,255))
cv2.line(dst_line, (50,250), (400,380), (25,100,255))
cv2.line(dst_line, (400,380), (200,150), (25,100,255))

cv2.imshow("line", dst_line)
cv2.waitKey(5000)
cv2.destroyAllWindows()

# 2. 矩形圆形绘制

- 矩形绘制API：cv2.rectangle()
    - 参数1：目标图片数据
    - 参数2：矩形左上角的起始点
    - 参数3：右下角
    - 参数4：颜色
    - 参数5：是否填充矩形框中的内容，
        - -1表示是填充
        - 若大于0，值越大，线条越粗

- 圆形绘制API：cv2.circle()
    - 参数1：目标图片数据
    - 参数2：圆心
    - 参数3：半径
    - 参数4：颜色
    - 参数5：是否填充矩形框中的内容，
        - -1表示是全填充
        - 若大于0，值越大，线条越粗

-  椭圆形绘制API：cv2.ellipse()
    - 参数1：目标图片数据
    - 参数2：圆心
    - 参数3：轴长：(长轴，短轴)
    - 参数4：偏转角度
    - 参数5：圆弧的起始角度
    - 参数6：圆弧的终止角度
    - 参数7：颜色
    - 参数8：是否填充矩形框中的内容，
        - -1表示是全填充
        - 若大于0，值越大，线条越粗
        
 
- 绘制任意多边形：
    

In [6]:
dst_rectangle = np.zeros((500,500,3),np.uint8)
dst_circle = np.zeros((500,500,3),np.uint8)
dst_ellipse = np.zeros((500,500,3),np.uint8)
dst_poly = np.zeros((500,500,3),np.uint8)


# cv2.rectangle(dst_rectangle, (50,100), (200,300), (255,0,0), -1)
cv2.rectangle(dst_rectangle, (50,100), (200,300), (255,0,0), 5)
cv2.circle(dst_circle, (250,250), (50), (0,255,0),2)
cv2.ellipse(dst_ellipse, (256,256), (150,100),0,0,180, (255,255,0), -1)


points = np.array([[150,50],[140,140],[200,170],[250,250],[150,50]])    # (5,2)
points.reshape((-1,1,2))    # 维度转换 (5,1,2)
cv2.polylines(dst_poly, [points], True, (0,255,255))    #如果去掉中括号，只是画四个点


# cv2.imshow("rectangle", dst_rectangle)
# cv2.imshow("circle", dst_circle)
# cv2.imshow("ellipse", dst_ellipse)
cv2.imshow("polylines", dst_poly)

cv2.waitKey(5000)
cv2.destroyAllWindows()

In [11]:
a = np.array([[150,50],[140,140],[200,170],[250,250],[150,50]])
b = a.reshape((-1,1,2))
print(a)
print("********")
print(b)

[[150  50]
 [140 140]
 [200 170]
 [250 250]
 [150  50]]
********
[[[150  50]]

 [[140 140]]

 [[200 170]]

 [[250 250]]

 [[150  50]]]


# 3. 文字图片绘制

- 文字绘制API：cv2.putText()

    - 参数1：目标图片数据
    - 参数2：文字内容
    - 参数3：起始坐标
    - 参数4：字体
    - 参数5：字体大小
    - 参数6：字体颜色
    - 参数7：字体粗细
    - 参数8：线条类型，line type

In [16]:
img0 = img.copy()

font = cv2.FONT_HERSHEY_SIMPLEX
text = "I LOVE U"

cv2.rectangle(dst_rectangle,(200,100),(500,400),(0,255,0),3)
cv2.putText(img0, text, (80,350), font, 1, (200,100,255),2, cv2.LINE_AA)

cv2.imshow("text", img0)
cv2.waitKey(5000)
cv2.destroyAllWindows()

In [19]:
# 图片绘制

img1 = img.copy()

height = int(img1.shape[0]*0.2)
width = int(img1.shape[1]*0.2)
img_resize = cv2.resize(img1,(width, height))

for i in range(0, height):
    for j in range(0, width):
        img1[i+10, j+20] = img_resize[i,j]
        
cv2.imshow("pic", img1)
cv2.waitKey(5000)
cv2.destroyAllWindows()